---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-api
  namespace: gemma
  labels:
    k8s-app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo-api
  template:
    metadata:
      name: demo-api
      labels:
        k8s-app: demo-api
    spec:
      containers:
      - name: demo-api
        image: vngr/demo-api-component:0.1.0
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: demo_api.conf.docker
          - name: SUBPATH
            value: /demo-api
          - name: DB_HOST
            value: postgres-demo-api
          - name: SECRET_KEY
            value: <REDACTED>
          - name: DB_PASSWORD
            value: <REDACTED>
          - name: SENTRY_DSN
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: demo-api
  namespace: gemma
  labels:
    k8s-app: demo-api
spec:
  selector:
    k8s-app: demo-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
